config/routes.rb
Rails.application.routes.draw do
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'leaderboard', to: 'home#leaderboard', as: :leaderboard
  post 'palettes/create', to: 'home#create_palette', as: :create_palette
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/palette.rb
class Palette < ApplicationRecord
  belongs_to :user
  validates :user, :row, :col, :color, presence: true
  scope :latest, -> { where("id in (select max(id) from palettes group by row, col)") }

  def as_json(options = {})
    {
      row: row,
      column: col,
      color: color,
      info: "#{user.username}, #{created_at.strftime('%d/%m/%Y')}"
    }
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :palettes, dependent: :destroy
  validates :username, :ip_address, presence: true

  def self.get_record_along_with_fav_color
    joins(:palettes).order("palettes_count desc").select("users.*, (select color from palettes where palettes.user_id = users.id  
      group by color having count(color)=(select max(t.color_count) from (select count(color) 
      color_count from palettes  where palettes.user_id = users.id group by color)t) limit 1) as fav_color").uniq
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_action :set_user
  helper_method :current_user
  
  def current_user
    @user
  end

  protected

  def set_user
    @user = User.find_by(ip_address: request.remote_ip)

    unless @user
      @user = User.create(username: "User-#{Time.now.to_i}", ip_address: request.remote_ip)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end  

  def leaderboard
    # get all the user along with their favourite color
    @users = User.get_record_along_with_fav_color
  end

  def create_palette
    @palette = current_user.palettes.new(palette_params)

    if @palette.save
      ActionCable.server.broadcast 'grids', grid: @palette.to_json
    end  
  end  

  protected

  def palette_params
    params.require(:palette).permit(:color, :row, :col)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/create_palette.js.erb
$(".create-palette-form").find(".color").val("");
<% if @palette.errors.empty? %>
  $(".alert").html("Grid has been successfully updated.").addClass("alert-success").show();
  ColorGrid.Palette.init("<%= j raw Palette.includes(:user).latest.to_json %>");
<% else %>
  $(".alert").html("<%= @palette.errors.full_messages.to_sentence %>").addClass("alert-success").show();
<% end %>

app/views/home/index.html.erb
<aside class="color-picker-container">
  <h3>Pick your Color</h3>
  <%= form_tag create_palette_path, class: "create-palette-form" do %> 
    <%= text_field_tag :color, '', required: true, class: 'color' %>
    <%= submit_tag 'Submit' %>
  <% end %>
</aside>
<section class="color-grid-container">
  <h3>Select the Grid</h3> 
  <section></section> 
</section>

<%= javascript_tag do %>
  ColorGrid.Palette.init("<%= j raw Palette.includes(:user).latest.to_json %>");
<% end %>

app/views/home/leaderboard.html.erb
<h2>Leaderboard</h2>
<table class="table table-striped">
  <thead>
   <tr>
    <td>Rank</td>
    <td>Username</td>
    <td>Favourite Color</td>
   </tr>
  </thead>
  <tbody>
   <% @users.each_with_index do |user,index|%>
    <tr>
     <td><%= index + 1 %></td>
     <td><%= user.username%></td>
     <td><span class="fav-color" style="background-color: <%= user.fav_color %>"></span> <%= user.fav_color %></td>
    </tr>
   <%end%>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ColorGrid</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <%= link_to "ColorGrid", root_path, class: "navbar-brand" %>
      <ul class="float-right navbar-nav">
        <li class="nav-item">
          <%= link_to "Dashboard", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Leaderboard", leaderboard_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <a class="username nav-link" href="#"><%= current_user.username %></a>
        </li>  
      </ul>
     
    </nav>    
    <div id="main-container">
      <p class="alert alert-success"></p>
      <div class="content-wrapper">
        <%= yield %>
      </div>
      <%= javascript_tag do %>
        <%= yield :javascript %>
      <% end %>
    </div>
  </body>
</html>